server:
  port: 8084

spring:
  application:
    name: CONFIGSERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AmirAli078/microservice-configuration
          clone-on-start: true