server:
  port: 8081

spring:
  application:
    name: USER-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/usermicro
    username: root
    password: Password420
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      auto-commit: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  config:
    import: optional:configserver:http://localhost:8084

# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka
#     fetch-registry: true
#   instance:
#     prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: health # Expose all actuator endpoints (use specific endpoints in prod, like "health", "info")
  endpoint:
    health:
      show-details: always # Show full health info in response
  health:
    circuitbreakers:
      enabled: true # Enables resilience4j circuit breaker health status



#resilience4j:
#  circuitbreaker:
#    instances:
#      ratingHotelBreaker:
#        registerHealthIndicator: true
#        slidingWindowSize: 10
#        minimumNumberOfCalls: 5
#        failureRateThreshold: 50
#        waitDurationInOpenState: 10s
#        permittedNumberOfCallsInHalfOpenState: 3
#        automaticTransitionFromOpenToHalfOpenEnabled: true
#        eventConsumerBufferSize: 10

resilience4j:
  retry:
    instances:
      ratingHotelRetry:
        max-attempts: 3
        wait-duration: 2s
        retry-exceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
        ignore-exceptions:
          - com.amir.user.service.exceptions.ResourceNotFoundException
